:Author: PensActius
:Email: pensactius@gmail.com
:Date: 17/03/2018
:Revision: version#
:License: Public Domain
:Project: YM_PlayerUSB

= Project: {Project}

Fork del proyecto original creado por _Florent Flament_.
```
Más información del proyecto original
-------------------------------------

More information can be found on my blog:

* [Streaming music to YM2149F][1]
* [Driving YM2149F sound chip with an Arduino][2]
* [Arduino Hello World without IDE][3]

Besides, a video showing the [YM2149 & Arduino circuit playing a tune][4] is
available.


[1]: http://www.florentflament.com/blog/streaming-music-to-ym2149f.html
[2]: http://www.florentflament.com/blog/driving-ym2149f-sound-chip-with-an-arduino.html
[3]: http://www.florentflament.com/blog/arduino-hello-world-without-ide.html
[4]: https://www.youtube.com/watch?v=MTRJdDbY048
```

Reproductor de archivos *YM* (Atari ST) usando el chip *YM2149* -o compatible como el *AY-3-8910*- y controlado por Arduino UNO (o Nano) originales. El formato YM no es más que un volcado de los 16 registros de 8 bits del chip YM2149 que se efectúa cada 1/50s. 

El proyect consta de dos partes. Un programa Arduino que _escucha_ por el puerto serie a 9600 bps la llegada de 16 bytes -correspondientes al volcado de los 16 registros-. Una vez recibidos los 16 bytes se escribe cada valor correspondiente al registro adecuado (byte 0 al registro 0, byte 1 al registro 2, etc.) como se muestra a continuación:

```
 Fill the "x" bits with the original chip value and set all other bits to 0.
	        _________________________________________________
			      Frame register detail
		¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
		    b7 b6 b5 b4 b3 b2 b1 b0
		 r0 x  x  x  x  x  x  x  x   Period voice A
		 r1             x  x  x  x   Fine period voice A
		 r2 x  x  x  x  x  x  x  x   Period voice B
		 r3             x  x  x  x   Fine period voice B
		 r4 x  x  x  x  x  x  x  x   Period voice C
		 r5             x  x  x  x   Fine Period voice C
		 r6          x  x  x  x  x   Noise period
		 r7       x  x  x  x  x  x   Mixer control
		 r8          x  x  x  x  x   Volume control A
		 r9          x  x  x  x  x   Volume control B
		r10          x  x  x  x  x   Volume control C
		r11 x  x  x  x  x  x  x  x   Envelope high period
		r12 x  x  x  x  x  x  x  x   Envelope low period
		r13             x  x  x  x   Envelope shape
		r14			     Data of I/O port A
		r15			     Data of I/O port B
		_________________________________________________
```
Otro programa escrito en Python `ym_streamer.py` se encarga de leer el archivo en formato *YM* y enviar los datos en el orden correcto -por defecto los datos de un fichero YM están guardados con _interleaving_-. La forma de usar este archiov es:
```
ym_streamer puerto_usb nombre_archivo_ym_descromprimido

p.ej

ym_streamer /dev/ttyUSB0 SONG1.YM
```

*Nota 1*: Es necesario una placa Arduino UNO (o Nano) original, no sirven versiones chinas debido al uso de instrucciones
del chip AVR propias).

*Nota 2*: Los archivos YM suelen estar comprimidos con el algoritmo _lha_ y por tanto hay que descomprimirlos primero. El programa _7z_ o _7zip_ los puede descomprimir sin problemas.


Detalles de programación:
-----------------------
_BV(n) es una macro del micro AVR que facilita crear la máscara adecuada de bits para poner bits a 1/0. 
Es equivalente a (1 << n) (uno shift left n veces).

Version compatible con el Shield YM2149 de PensActius:
  
  D2 .. D9  DATOS
  D10       BDIR
  D11       BC1
  
Traduccion Pines digitales a PORTx (aka PBx, PDx):
  
  PD2 .. PD7 (Avr) = D2 .. D7 (Arduino)
  PB0 .. PB7 (Avr) = D8 .. D9 (Arduino)
  PB2 .. PB3 (Avr) = D10 .. D11 (Arduino)


== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch
  
  D2 .. D9  connect to DAx into YM2149
  D11       Connects to Clk into YM2149
  A2        connects to BC1 into YM2149
  A3        connects to BDIR into YM2149
  BC2       is always connected to +5V

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact pensactius <pensactius@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
