:Author: pensactius
:Email: pensactius@gmail.com
:Date: 17/03/2018
:Revision: version#
:License: Public Domain

= Project: {Project}

NOTAS:
------
_BV(n) es una macro del micro AVR que facilita crear la máscara adecuada de bits para poner bits a 1/0. 
Es equivalente a (1 << n) (uno shift left n veces).

Version compatible con el Shield YM2149 de PensActius:
  
  D2 .. D9  DATOS
  D10       BDIR
  D11       BC1
  
Traduccion Pines digitales a PORTx (aka PBx, PDx):
  
  PD2 .. PD7 (Avr) = D2 .. D7 (Arduino)
  PB0 .. PB7 (Avr) = D8 .. D9 (Arduino)
  PB2 .. PB3 (Avr) = D10 .. D11 (Arduino)


== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch
  
  D2 .. D9  connect to DAx into YM2149
  D11       Connects to Clk into YM2149
  A2        connects to BC1 into YM2149
  A3        connects to BDIR into YM2149
  BC2       is always connected to +5V

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact pensactius <pensactius@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
